"""
Pydantic models (schemas) for API data validation and serialization.

This file defines the data structures used for validating incoming API requests
and for formatting outgoing API responses. These Pydantic models are distinct
from the SQLAlchemy ORM models, providing a clear separation between the
database layer and the API layer.

- `JobBase`: A base schema with common attributes.
- `JobCreate`: The schema used for the request body when creating a new job.
- `Job`: The schema used for API responses, including all database-generated fields.
"""
from pydantic import BaseModel, ConfigDict
from typing import Optional
from datetime import datetime
from .models import JobStatus

# Pydantic models (schemas) for API data validation.

class JobBase(BaseModel):
    """
    Base schema for a Job, containing common attributes.
    """
    name: str
    schedule: Optional[str] = None

class JobCreate(JobBase):
    """
    Schema used for creating a new job. Inherits from JobBase.
    """
    pass

class Job(JobBase):
    """
    Schema used for representing a job in API responses.
    Includes attributes that are generated by the database.
    """
    id: int
    status: JobStatus
    last_run: datetime
    created_at: datetime

    # This configuration tells Pydantic to read the data even if it is not a dict,
    # but an ORM model (or any other arbitrary object with attributes).
    model_config = ConfigDict(from_attributes=True)
